name: Shell Commands

on:
  push:
    branches: [ master ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: echo a string
        run: echo "Hello World"
      - name: checks
        run:  npm -v       