name: Shell Commands

on:
  push:
    branches: [ master ]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: "node -v \n npm -v \n"          