name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scrip
        run: "node -v \n npm -v \n"          